version: "3.8"

services:
  mpi-master:
    build: .
    container_name: mpi-master
    hostname: mpi-master
    networks:
      - mpi-net
    volumes:
      - shared-keys:/root/.ssh
    entrypoint: >
      bash -c "
        /usr/sbin/sshd &&
        sleep 3 &&
        echo 'mpi-master slots=2' >  /app/hostfile &&
        echo 'mpi-worker1 slots=2' >> /app/hostfile &&
        echo 'mpi-worker2 slots=2' >> /app/hostfile &&
        mpirun --hostfile /app/hostfile -np 6 /app/stats
      "

  mpi-worker1:
    build: .
    container_name: mpi-worker1
    hostname: mpi-worker1
    networks:
      - mpi-net
    volumes:
      - shared-keys:/root/.ssh

  mpi-worker2:
    build: .
    container_name: mpi-worker2
    hostname: mpi-worker2
    networks:
      - mpi-net
    volumes:
      - shared-keys:/root/.ssh

networks:
  mpi-net:
    driver: bridge

volumes:
  shared-keys: